[build]
  command = "npm run build" # o el comando que necesites para construir tu aplicación
  functions = "functions" # la carpeta donde estarán las funciones de Netlify (funciones serverless)

[[redirects]]
  from = "/*"
  to = "/server/index.js"
  status = 200
