[build]
  command = "npm run build"  # El comando para construir tu proyecto (o el que sea necesario)
  publish = "dist"           # La carpeta que contiene los archivos a desplegar (por ejemplo, después de ejecutar npm run build)

[[redirects]]
  from = "/*"
  to = "/client/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Connection = "upgrade"
    Upgrade = "websocket"
