[build]
  command = "npm run build" 
  functions = "functions" 
  
[[redirects]]
  from = "/*"
  to = "/client/index.html"
  status = 200

[[redirects]]
  from = "/*" 
  to = "/server/index.js" 
  status = 200 